POST http://localhost:8000/events
Content-Type: application/json

{
    "title": "Salão do Automóvel 2025",
    "details": "Um evento para os apaixonados por Automobilismo",
    "maximumAttendees": 100
}

###

POST http://localhost:8000/events/3c23eb02-d98c-4adc-9735-5be0392a3748/attendees
Content-Type: application/json

{
    "name": "André Sperendio",
    "email": "andresperendio97@gmail.com"
}

###

GET http://localhost:8000/events/3c23eb02-d98c-4adc-9735-5be0392a3748

###

GET http://localhost:8000/attendees/8/badge

###

GET http://localhost:8000/attendees/9/check-in

###

GET http://localhost:8000/events/3c23eb02-d98c-4adc-9735-5be0392a3748/attendees

###

GET http://localhost:8000/events/3c23eb02-d98c-4adc-9735-5be0392a3748/attendees?query=andré